name: Build and Lint

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-lint:
    name: Build and Lint

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          show-progress: false
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - run: npm run build

      - run: npm run lint
